<?php
/**
 * Implementation of hook_enable
 */
function openberkeley_faq_enable() {
  $vocab = taxonomy_vocabulary_machine_name_load('faqs');
  $terms = taxonomy_get_tree($vocab->vid,0,1,false);
  if (isset($vocab->vid) && count($terms) == 0) {
  	$term = new stdClass();
    $term->name = 'General';
    $term->vid = $vocab->vid;
    $term->description = 'General FAQs';
    taxonomy_term_save($term);
  }
}
